config/routes.rb
Rails.application.routes.draw do
  
  resources :authors, only: [:index, :show]
  resources :books, only: [:index, :show, :new, :create, :edit, :update] 
  resources :reviews
  resources :lists, only: [:new, :create, :index, :edit, :update]
  
  resources :users
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#logout"
  get '/analytics', to: "application#analytics"
  root 'books#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books

  def self.search(search)
        
    if search
      result = Author.select {|a| a.name.include? (search.capitalize)}
    else
      Author.all
    end

  end

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :reviews
  has_many :lists

  accepts_nested_attributes_for :reviews

  validates :title, uniqueness: {case_sensitive: false}
  validates :author, presence: true
  validates :category, presence: true

  def average_rating
    review_count = self.reviews.size.to_f
    review_ratings = self.reviews.map(&:rating)
    review_sum = review_ratings.sum
    if review_count == 0
      return "No ratings yet" 
    else
      review_sum / review_count
    end
  end
end

app/models/list.rb
class List < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
  validates :rating, presence: true, :inclusion => 1..5
  #validates :rating, numericality: true, :in => 1..5
end

app/models/user.rb
class User < ApplicationRecord
    
    has_secure_password
    has_many :reviews
    has_many :lists
    
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  def current_user
    if @current_user
      return @current_user
    elsif !session[:user_id].blank?
      @current_user = User.find(session[:user_id])
    else 
      return nil
    end
  end

  def logged_in?
    !!current_user
  end

  def authorized
    redirect_to login_path unless logged_in?
  end
  
  def analytics
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :find_author, only: [:show]

  def index
    @authors = Author.search(params[:search])
  end

  def show
    
  end
  private
  def find_author
    @author = Author.find_by(id: params[:id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update]
  before_action :authorized, only: [:new, :create, :edit, :update]

  def index
    if params[:category]
      if params[:category] == "All"
        @books = Book.all
      else
        @books = Book.select {|b| b.category == params[:category]}
      end
    else
      @books = Book.all
    end
  end

  def new
    @book = Book.new
    @categories = Book.all.collect {|b| b.category}.uniq
    # @statuses = List.all.collect {|l| l.status}.uniq
    @book.reviews.build
    # @book.lists.build
  end

  def create
    
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book)
    else
      @book.reviews.build
      # @book.lists.build
      render :new
    end
  end

  def show
    cookies[:book_id] = @book.id
    if @list
      @list = List.find {|l| l.book_id == @book.id && l.user_id == current_user.id}
    end
  end

  def edit
    @categories = Book.all.collect {|b| b.category}.uniq
  end

  def update
    @categories = Book.all.collect {|b| b.category}.uniq
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  private
  def find_book
    @book = Book.find_by(id: params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author_id, :description, :purchase_url, :image_url, :category, reviews_attributes: [:id, :comment, :rating])
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_book, only: [:new, :create, :edit, :update]

  def index
    @lists = List.all
  end
  
  def new
    @list = List.new
  end

  def create
    @list = List.create(status: list_params[:status], user_id: current_user.id, book_id: @book.id)
    @statuses = List.all.collect {|l| l.status}.uniq
    redirect_to book_path(@book)
  end

  def edit
    @list = List.find {|l| l.book_id == @book.id && l.user_id == current_user.id}
  end

  def update
    @list = List.find {|l| l.book_id == @book.id && l.user_id == current_user.id}
    @list.update(status: list_params[:status], user_id: current_user.id, book_id: @book.id)
    redirect_to book_path(@book)
  end

  private

  def list_params
    params.require(:list).permit(:status, :user_id, :book_id)
  end

  def find_book
    @book = Book.find(cookies[:book_id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_book
  before_action :authorized

  def new
    @review = Review.new
    # byebug
    # @review = @book.reviews.build
    # raise params.inspect
  end
  
  def create
    @review = Review.new(comment: review_params[:comment], rating: review_params[:rating], book_id: @book.id, user_id: current_user.id)
    if @review.save
      List.create(status: "Read", user_id: current_user.id, book_id: @book.id)
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def edit
    @review = Review.find_by(id: params[:id])
  end

  def update
    @review = Review.find_by(id: params[:id])
    @review.update(comment: review_params[:comment], rating: review_params[:rating], book_id: @book.id, user_id: current_user.id)
    if @review.save
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    if @review.destroy
      flash[:success] = 'Review was successfully deleted.'
      redirect_to user_path(current_user)
    else
      flash[:error] = 'Something went wrong'
      redirect_to user_path(current_user)
    end
  end
  

  private

  def review_params
    params.require(:review).permit(:comment, :rating, :user_id, :book_id)
  end

  def find_book
    @book = Book.find(cookies[:book_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to books_path
        else
            flash[:error] = "No user found with that email and password combination."
            render :new
        end
    end

    def logout
        session.clear
        redirect_to login_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to books_path
    else
      render :new
    end
  end

  def show
    if params[:status]
      if params[:status] == "All"
        @books = List.select {|l| l.user_id == current_user.id}.map {|l| l.book}
      else
        lists = List.select {|l| l.status == params[:status] && l.user_id == current_user.id}
        @books = lists.map {|l| l.book}
      end
    else
      @books = List.select {|l| l.user_id == current_user.id}.map {|l| l.book}
    end
  end

  def edit
  end

  def update 
    if @user.save
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  

  private

  def find_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/analytics.html.erb
<div class="row">
  <div class="col-sm">
    <h1> WhyA Reads Analytics</h1>
  </div>
</div>

<p>This app currently has <%= Book.count %> books, written by <%= Author.count %> authors.</p>
<p>This app has <%= User.count %> users, who have written <%= Review.count %> reviews.</p>
<% user_most_reviews = User.all.max_by {|user| user.reviews.count} %>
<p><%=  user_most_reviews.name %> has made the most reviews, with <%= user_most_reviews.reviews.count %>. Kudos to <%=  user_most_reviews.name %>!</p>
<% most_recent_user = User.order(created_at: :desc).limit(1) %>
<p>Our most recent user is <%= most_recent_user.first.name %>. Welcome to the app!
<% most_read = List.where(status: "Read").map(&:book_id) %>
<% top_read_book_id = most_read.max_by {|i| most_read.count(i) } %>
<% if List.where(status: "Read").empty? %>
    <p>No one has put a book on their "read" bookshelf.</p>
<% else %>
    <p>Currently, <%= Book.find(top_read_book_id).title %> is the book that the most people have read.</p>
<% end %>
<% books_with_ratings = Book.select {|book| book.reviews.any? } %>
<%  highest_rating = books_with_ratings.max_by{|book| book.average_rating} %>
<p>The highest rated book is <%= highest_rating.title %>, with a rating of <%= highest_rating.average_rating.to_i %> out of 5. Folks love it!</p>

app/views/authors/index.html.erb
<h1>Authors</h1>

<h2>Search Author: </h2>
<%= form_tag authors_path, method: "GET" do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" %>
<% end %>

<ul>
<% @authors.each do |author| %>
  <li><%= link_to  author.name, author_path(author) %></li>
<% end %>
</ul>



  
  

app/views/authors/show.html.erb
<div class="row">
 
    <div class="col-md-4">
      <%= image_tag @author.image, class: "author-image" %>
    </div>

    <div class="col-md-8">
      <h1><%= @author.name %></h1>
      <p><%=  @author.bio %></p>
    </div>
    
    <h4>Books by <%= @author.name %></h4>
  </div>
  
  <ul>
  <% @author.books.each do |book| %>
  <li><%= link_to  book.title, book_path(book)%></li>
  <% end %>
  </ul>
  <p><%= link_to  "Authors Main Page", authors_path %>

app/views/books/_form.html.erb
  <%= form_for @book do |f| %>
    <div class="form-group">
      <%= f.label "Title" %>
      <%= f.text_field :title, { class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= f.label "Author" %>
      <%= f.collection_select :author_id, Author.all, :id, :name, {}, {required: 'true', autofocus: 'true', class: 'form-control'} %> 
    </div>
    <div class="form-group">
      <%= f.label "Category" %>
      <%= f.select(:category, @categories, {}, {:class => 'form-control'}) %>
    </div>
    <div class="form-group"> 
      <%= f.label "Description" %>
      <%= f.text_area :description, class: 'form-control'  %> 
    </div>
    <div class="form-group">
      <%= f.label "Purchase Link" %>
      <%= f.text_field :purchase_url, class: 'form-control'  %> 
    </div>
    <div class="form-group"> 
      <%= f.label "Image Link" %>
      <%= f.text_field :image_url,class: 'form-control'  %> 
    </div>
    
    <%= f.button({ class: 'btn btn-primary' }) %> 
    
  <% end %>

app/views/books/edit.html.erb
<h1>Edit <%= @book.title %>:</h1>

<%= render "form" %>

app/views/books/index.html.erb
<h1>WhyA Reads - Review YA Books and Track Your Reading</h1>

<div class="book-search">
<%= form_tag books_path, method: "get" do %>
  <%= select_tag :category, options_for_select(["All", "Coming of Age", "Fantasy", "Fiction", "LGBT Friendly", "Science Fiction", "Thriller"]),
       prompt: "Filter by category" %>
  <%= submit_tag "Submit", class:"btn btn-primary" %>
<% end %>
</div>

<div class="row">

  <% @books.each do |book| %>

    <div class="mcol-md-3">

      <a href="/books/<%=book.id %>"><%= image_tag book.image_url, class: "book-image" %>

    </div>

  <% end %>

</div>

app/views/books/new.html.erb
  <h1>Add a new book</h1>


  <%= render "form" %>

app/views/books/show.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<h1><%= @book.title %></h1>
<h3>Average Rating: <% @book.average_rating.to_i.times do %>
    <span class="fa fa-star checked"></span>
<% end %>
<h3>Author: <%= link_to @book.author.name, author_path(@book.author) %></h3>
 
<div class="row">
 
    <div class="col-md-4">
        <%= image_tag(@book.image_url, height: 400)  %><br>
 
        <% if current_user %>
            <% if !current_user.lists.any? {|l| l.book_id == cookies[:book_id]} %>
                <p><%= link_to "Add this book to your bookshelf", new_list_path %></p>
            <% else %>
                <% list = current_user.lists.find {|list| list.book_id == @book.id} %><br>
                <p><%= link_to "Change bookshelf", edit_list_path(list), class: 'btn btn-primary' %></p>
            <% end %>
        <% end %>
    </div>
 
    <div class="col-md-8">
 
        <h5>Category: <%= @book.category %></h5>
        <p><strong>Description:</strong> <%= @book.description %></p>
        <p><%= link_to  "Buy Here", @book.purchase_url %></p>
 
        <% if current_user %>
        <p><%= link_to "Edit this Book", edit_book_path(@book), class: 'btn btn-primary' %></p>
        <% end %>
 
        <p><%= link_to  "Books Main Page", books_path  %>
 
    </div>
</div>
<% if current_user %>
<div><%= link_to  "Add Book Review", new_review_path, class: 'btn btn-primary' %></div><br>
<% end %>
 
<% if !@book.reviews.empty? %>
    <div>Reviews for <%= @book.title %>: </div>
 
    <ul>
        <% @book.reviews.each do |review| %>
            
            <li><%= review.user.name %> says: <%= review.comment %> -  Rating: 
            <% review.rating.to_i.times do  %>
                <span class="fa fa-star checked"></span>
            <% end %>
            </li>
        <% end %>
    </ul>
<% else %>
    <p>There are no reviews for this book yet. Be the first!</p>
<% end %>
 

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhyaReads</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar  navbar-expand-lg bg-gradient-info  mr-auto">
        
          <%= link_to  "Home", root_path, class: 'nav-link nav-item text-white' %>
          <%= link_to  "Authors", authors_path, class: 'nav-link nav-item text-white' %>
          <% if current_user %>
              <%= link_to "Add a New Book", new_book_path, class: 'nav-link nav-item text-white' %>
              <%= link_to  "Go to my Profile", user_path(current_user.id), class: 'nav-link nav-item text-white' %>
              <%= link_to "Logout", logout_path, method: "DELETE", class: 'nav-link nav-item text-white' %>
            <% else %>
              <%= link_to "Login", login_path, class: 'nav-link text-white' %></li>
          <% end %>
        
    </nav>
    <div class="container">
    <%= yield %>
    </div>
    
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
  <div class="input-group mb-3">
    <%= f.select :status, options_for_select(["Currently reading", "Want to read", "Read"]), {}, class: 'form-control' %>
    <div class="input-group-append">
      <%= f.submit  "Add to Shelf", class: 'btn btn-outline-primary' %>
    </div>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Change bookshelf for <%= @list.book.title %></h1>

<%= render "form" %>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<h1> Add <%= @book.title %> to your shelf </h1>

<%= render "form" %>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>

app/views/reviews/_form.html.erb
<div>
<h2><%= @book.title %></h2>
<%= form_for @review do |form| %>
   
        <div class="form-group">
        <%= form.label :rating %>
        <%= form.select :rating, (1..5), {}, {:class => 'form-control'} %>
        </div>
        <div class="form-group">
        <%= form.label :comment %>
        <%= form.text_area :comment, class: 'form-control' %>
        </div>
        
        <%= form.button :submit, class: 'btn btn-primary' %>    
    
<% end %>



</div>

app/views/reviews/edit.html.erb
<h1>Edit This Review</h1>
<%= render 'form' %>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<h1>Create A Review</h1>
<%= render "form" %>
<%= link_to  "Back", book_path(@book) %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Create a new User or <%= link_to  "Login", login_path %>:</h1>

<%= form_for @user do |f| %>
    <div class="form-group"> <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %> </div>
    <div class="form-group"><%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %></div>
    <div class="form-group"><%= f.label "Password" %>
    <%= f.password_field :password, class: "form-control" %></div>
    <%= f.submit(class: 'btn btn-primary') %>
<% end %>

app/views/users/show.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="jumbotron">
<h1>Hello <%= @user.name %>!</h1>

<h3>All My Books</h4>

<%= form_tag user_path(current_user.id), method: "get" do %>
  <%= select_tag :status, options_for_select(["All", "Currently reading", "Want to read", "Read"]),
       prompt: "Select Bookshelf" %>
  <%= submit_tag "Submit", class:"btn btn-primary" %>
<% end %>

<ul>
<% @books.each do |book| %>
  <li><%= link_to book.title, book_path(book) %></li>
<% end %>
</ul>

<h3>My Reviews</h3>
<% if @user.reviews.any? %>
  <p>You have reviewed <%= @user.reviews.count %> books. Thanks!</p>
  <% @user.reviews.each do |review| %>
  <p><%= link_to review.book.title, book_path(review.book.id) %>: <%= review.comment %> - rating: <% review.rating.to_i.times do %>
    <span class="fa fa-star checked"></span>
  <% end %><br>
    <%= link_to  "Edit Review", edit_review_path(review.id), class: 'btn btn-info' %>  <%= link_to  "Delete Review", review_path(review), class: 'btn btn-danger',method: :delete, data: {confirm: 'Are you sure?'} %></p>
  <% end %>
<% else %>
  <p>You don't have any reviews yet.</p>
<% end %>
<div>